// <auto-generated />
namespace RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V106_Fluent_Api : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V106_Fluent_Api));
        
        string IMigrationMetadata.Id
        {
            get { return "202006081330498_V1.0.6_Fluent_Api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
