// <auto-generated />
namespace RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V102_Seed_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V102_Seed_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051133238_V1.0.2_Seed_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
