// <auto-generated />
namespace RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V101__JSON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V101__JSON));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121008503_V1.0.1__JSON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
